services:
  frontend:
    build:
      context: ../frontend
    image: vanwallet-react:local
    container_name: vanwallet_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_started
    networks:
      - vanwallet-network

  backend:
    build:
      context: .
    image: vanwallet-backend:local
    container_name: vanwallet_backend
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8080"
    depends_on:
      migration:
        condition: service_completed_successfully
      seeder: # Menjamin backend baru jalan setelah database terisi data dummy
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - vanwallet-network

  postgres:
    image: postgres:17-alpine
    container_name: vanwallet_postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 3s
      timeout: 10s
      retries: 10
    networks:
      - vanwallet-network

  migration:
    image: migrate/migrate:v4.18.3
    container_name: vanwallet_migration
    restart: "no"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./database/migrations:/migrations:ro
    entrypoint: sh -c
    command: >
      "sleep 3 && 
      /migrate -path /migrations -database postgres://${DB_USER}:${DB_PASS}@postgres:5432/${DB_NAME}?sslmode=disable up"
    networks:
      - vanwallet-network

  seeder:
    image: postgres:17-alpine
    container_name: vanwallet_seeder
    restart: "no"
    env_file:
      - .env
    depends_on:
      migration: # WAJIB: Tunggu tabel dibuat dulu lewat migrasi
        condition: service_completed_successfully
    volumes:
      - ./database:/seed-dir:ro
    # Menjalankan perintah psql untuk mengeksekusi seed.sql ke container postgres
    command: >
      sh -c "PGPASSWORD=$${DB_PASS} psql -h postgres -U $${DB_USER} -d $${DB_NAME} -f /seed-dir/seed.sql"
    networks:
      - vanwallet-network

  redis:
    image: redis:7-alpine
    container_name: vanwallet_redis
    restart: unless-stopped
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 10s
      retries: 10
    networks:
      - vanwallet-network

volumes:
  postgres_data:

networks:
  vanwallet-network:
    driver: bridge