# ─────────────────────────────────────────────
# Stage 1 — Build
# ─────────────────────────────────────────────
FROM golang:1.26.3-alpine3.23 AS builder

# git is required for go mod download
RUN apk add --no-cache git

WORKDIR /app

# Cache dependency downloads before copying source
COPY go.mod go.sum ./
RUN go mod download

# Copy full source tree
COPY . .

# Build a statically-linked binary (CGO disabled — pgx/v5 is pure Go)
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -ldflags="-s -w" -o vanwallet ./cmd/main.go

# ─────────────────────────────────────────────
# Stage 2 — Runtime
# ─────────────────────────────────────────────
FROM alpine:3.23

# ca-certificates for any TLS outbound calls; tzdata for proper timestamps
RUN apk add --no-cache ca-certificates tzdata

WORKDIR /app
# Copy binary from builder
COPY .env .env
COPY --from=builder /app/vanwallet .

# Copy static assets served at /img
COPY --from=builder /app/public ./public

# Copy Swagger docs generated by swag
COPY --from=builder /app/docs ./docs

EXPOSE 8080

ENTRYPOINT ["./vanwallet"]
