services:
  frontend:
    image: ghcr.io/rivando-al-rasyid/vanwallet-react:latest
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: ghcr.io/rivando-al-rasyid/vanwallet-backend:latest
    container_name: vanwallet_backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      # migration:
      #   condition: service_completed_successfully
      redis:
        condition: service_healthy

  postgres:
    image: postgres:17-alpine
    container_name: vanwallet_postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 2s
      timeout: 10s
      retries: 5

  # migration:
  #   image: migrate/migrate:v4.18.3
  #   container_name: vanwallet_migration
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   volumes:
  #     - ./backend/database/migrations:/migrations
  #   command:
  #     [
  #       "-path",
  #       "/migrations",
  #       "-database",
  #       "postgres://${DB_USER}:${DB_PASS}@postgres:5432/${DB_NAME}?sslmode=disable",
  #       "up"
  #     ]

  redis:
    image: redis:7-alpine
    container_name: vanwallet_redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 10s
      retries: 5

volumes:
  postgres_data: