ALTER TABLE "profiles"
    ADD FOREIGN KEY ("user_id") REFERENCES "users"("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "favorites"
    ADD FOREIGN KEY ("user_id") REFERENCES "users"("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "favorites"
    ADD FOREIGN KEY ("target_user_id") REFERENCES "users"("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_pins"
    ADD FOREIGN KEY ("user_id") REFERENCES "users"("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tokens"
    ADD FOREIGN KEY ("user_id") REFERENCES "users"("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "wallets"
    ADD FOREIGN KEY ("user_id") REFERENCES "users"("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "topups"
    ADD FOREIGN KEY ("wallet_id") REFERENCES "wallets"("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transactions"
    ADD FOREIGN KEY ("wallet_id") REFERENCES "wallets"("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transfers"
    ADD FOREIGN KEY ("transaction_id") REFERENCES "transactions"("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transfers"
    ADD FOREIGN KEY ("recipient_transaction_id") REFERENCES "transactions"("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "expenses"
    ADD FOREIGN KEY ("transaction_id") REFERENCES "transactions"("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "withdrawals"
    ADD FOREIGN KEY ("transaction_id") REFERENCES "transactions"("id") DEFERRABLE INITIALLY IMMEDIATE;

